import React from 'react';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import CardList from '../components/CardList';
import useFetchPublicRepos from '../hooks/useFetchPublicRepos';
import Footer from '../components/Footer';
import Title from '../components/Title';
import Description from '../components/Description';

const GitHubRepositoryTemplate: React.VFC = () => {
  const publicReposRes = useFetchPublicRepos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title />
        <Description filename="src/pages/repos.tsx" />
        {publicReposRes.items == null ? (
          ''
        ) : (
          <CardList items={publicReposRes.items} />
        )}
      </main>

      <Footer />
    </div>
  );
};

export default GitHubRepositoryTemplate;
