import React from 'react';
import { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Footer from '../components/Footer';

type Props = {
  nowDatetime: string;
};

const IsrPage: NextPage<Props> = ({ nowDatetime }: Props) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className={styles.description}>現在日時は {nowDatetime}</p>
    </main>

    <Footer />
  </div>
);

// eslint-disable-next-line @typescript-eslint/require-await
export const getStaticProps: GetStaticProps = async () => {
  const now = new Date();

  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const date = now.getDate();
  const hour = now.getHours();
  const min = now.getMinutes();
  const sec = now.getSeconds();

  const nowDatetime = `${year}年${month}月${date}日${hour}:${min}:${sec}`;

  return {
    props: { nowDatetime },
    revalidate: 300,
  };
};

export default IsrPage;
