import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import CardList from '../components/CardList';

const reposPage: NextPage = () => {
  const items = [
    {
      id: 1,
      title: 'portfolio-frontend',
      url: 'https://github.com/nekochans/portfolio-frontend',
      description: 'GitHub Organization 「nekochans」の説明用Webサイト',
    },
    {
      id: 2,
      title: 'nekochans-terraform',
      url: 'https://github.com/nekochans/nekochans-terraform',
      description: 'nekochans紹介サイトのインフラ管理を行う',
    },
    {
      id: 3,
      title: 'portfolio-backend',
      url: 'https://github.com/nekochans/portfolio-backend',
      description:
        'GitHub Organization 「nekochans」の説明用Webサイトのバックエンド',
    },
    {
      id: 4,
      title: 'lgtm-cat-frontend',
      url: 'https://github.com/nekochans/lgtm-cat-frontend',
      description:
        'lgtm-cat（サービス名 LGTMeow https://lgtmeow.com) のフロントエンド用',
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>src/pages/repos.tsx</code>
        </p>

        <CardList items={items} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default reposPage;
